project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs

execute: 
    freeze: auto

resources:
  - "files/**"

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl


# Metadata stuff
pagetitle: "{{< var title >}}"
description-meta: "{{< var description >}}"
author-meta: "Roger Beecham"


website:
  title: "Roger Beecham"
  description: "Roger Beecham is Associate Professor in Visual Data Science at University of Leeds, researching, teaching and applying visual methods in social science data analysis ."
  favicon: "/files/favicon.png"
  site-url: "https://github.com/rogerbeecham/rogerbeecham.github.io"
  repo-url: "https://www.roger-beecham.com"
  
  twitter-card: 
    image: "/files/profiles/profile.png"
    card-style: summary_large_image
    creator: "@rjbeecham"
    site: "@rjbeecham"


  navbar:
    pinned: true

    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - text: Blog
        file: blog/index.qmd
      - href: research/index.qmd
        text: Research
      - href: projects/index.qmd
        text: Projects
      - href: teaching/index.qmd
        text: Teaching
      - text: "Now"
        href: now/index.qmd
        
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:r.j.beecham@leeds.ac.uk"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/rogerbeecham
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/rjbeecham.bsky.social
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/roger-beecham-a98860241/
    rel: me

  page-footer:
     left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Roger Beecham | Design by  [Andrew Heiss](https://www.andrewheiss.com/)</span> 
       <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>
     center: |
       <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
     right: |
       <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
       <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme:
      - html/rb.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
