---
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
    ratio: '16:9'
    highlightStyle: github
    highlightLines: true
    slideNumberFormat: ''
    seal: false
---

## Minerva Ultra upgrade

???

* Instructional session.
* Tell you about the Minerva Upgrade.
* Say where to get help.
* Demonstrate the new module layout.
* How to get going with minimum viable product.
* Things to discuss in terms of what we retain/drop.

* Upshot is ...

--
> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a template

--

### Resources

* [DES upgrade pages](https://desystemshelp.leeds.ac.uk/news_updates_categories/minerva-upgrade/)

* [Staff guide](https://desystemshelp.leeds.ac.uk/minerva-staff/get-started/using-the-module-template-and-top-tips-for-building-modules-in-ultra-course-view/)

* [Diffs](https://desystemshelp.leeds.ac.uk/minerva-staff/get-started/original-vs-ultra-differences/)

* [Edward Wilson-Stephens's video walkthroughs](https://web.microsoftstream.com/video/866e6666-8d6f-4634-8901-0cdf31bf09ef)

---

## Minerva Ultra upgrade

> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a **template**
--


### Hierarchical layout : Constraints

.tiny-font[
```
+-- Learning module | Folder
|   +-- Folder
|       +-- Document | Link Test Assignment | ...
|   +-- Document
|   +-- Link
|   +-- Test Assignment
|   +-- Discussion
|   +-- Journal
```
]

???

Module Content...
Contains either:
Learning Module | Folder

... Learning Module | Folder
Contains either:
Learning module / Folder ...


---

## Minerva Ultra upgrade

> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a **template**

### Hierarchical layout : Adding content

.tiny-font[
```
+-- Module Content
|   +-- Information -- Start Here
|   +-- Assessment and Feedback
|   +-- Session 1 :
|   +-- Session 2 :
|   +-- Session n :
|   +-- Reading List
|   +-- Mediasite
|   +-- Study skills
```
]

---


## Minerva Ultra upgrade

> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a **template**

### Hierarchical layout : Assessment


.tiny-font[
```
+-- Module Content
|   +-- Information -- Start Here
|   +-- Assessment and Feedback
|       +-- Submit my work
|           +-- Turnitin <Content Market>
|   +-- Session 1 :
|   +-- Session 2 :
|   +-- Session n :
|   +-- Reading List
|   +-- Mediasite
|   +-- Study skills
```
]

???

How to add information ...
Copy from previous module : Assignment brief

---

## Minerva Ultra upgrade

> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a **template**

### Questions : On layout, others

---

## Minerva Ultra upgrade

> Modules do not roll-over in usual way and need to be "re-built" for 2022/3 AY following a **template**

### Discussion : Handbooks

--

poll:

[`http://etc.ch/DAec`](http://etc.ch/DAec)
